### YamlMime:ManagedReference
items:
- uid: System.Windows.Media.Converters.PointCollectionValueSerializer
  id: PointCollectionValueSerializer
  children:
  - System.Windows.Media.Converters.PointCollectionValueSerializer.#ctor
  - System.Windows.Media.Converters.PointCollectionValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Media.Converters.PointCollectionValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Media.Converters.PointCollectionValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Media.Converters.PointCollectionValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  langs:
  - csharp
  name: PointCollectionValueSerializer
  nameWithType: PointCollectionValueSerializer
  fullName: System.Windows.Media.Converters.PointCollectionValueSerializer
  type: Class
  summary: "实例之间进行转换<xref:System.String>的实例与<xref href=&quot;System.Windows.Media.PointCollection&quot;> </xref>。</xref:System.String>"
  remarks: "此类通常仅供<xref:System.Windows.Markup.Primitives.MarkupWriter>用于序列化目的。</xref:System.Windows.Markup.Primitives.MarkupWriter>"
  syntax:
    content: 'public class PointCollectionValueSerializer : System.Windows.Markup.ValueSerializer'
  inheritance:
  - System.Windows.Markup.ValueSerializer
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Windows.Media.Converters.PointCollectionValueSerializer.#ctor
  id: '#ctor'
  parent: System.Windows.Media.Converters.PointCollectionValueSerializer
  langs:
  - csharp
  name: PointCollectionValueSerializer()
  nameWithType: PointCollectionValueSerializer.PointCollectionValueSerializer()
  fullName: System.Windows.Media.Converters.PointCollectionValueSerializer.PointCollectionValueSerializer()
  type: Constructor
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Converters
  summary: "初始化的新实例<xref href=&quot;System.Windows.Media.Converters.PointCollectionValueSerializer&quot;></xref>类。"
  syntax:
    content: public PointCollectionValueSerializer ();
    parameters: []
  overload: System.Windows.Media.Converters.PointCollectionValueSerializer.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Media.Converters.PointCollectionValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.PointCollectionValueSerializer
  langs:
  - csharp
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: PointCollectionValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.PointCollectionValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Converters
  summary: "确定是否从转换给定<xref:System.String>到实例<xref href=&quot;System.Windows.Media.PointCollection&quot;></xref>可以。</xref:System.String>"
  remarks: "此方法始终返回`true`。"
  syntax:
    content: public override bool CanConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: "要计算以供转换的字符串。"
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "用于转换的上下文信息。"
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果可以转换的值;否则为<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.Windows.Media.Converters.PointCollectionValueSerializer.CanConvertFromString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Media.Converters.PointCollectionValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.PointCollectionValueSerializer
  langs:
  - csharp
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: PointCollectionValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.PointCollectionValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Converters
  summary: "确定的实例时，如果<xref href=&quot;System.Windows.Media.PointCollection&quot;></xref>可以转换为一种<xref:System.String>。</xref:System.String>"
  syntax:
    content: public override bool CanConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: "实例<xref href=&quot;System.Windows.Media.PointCollection&quot;></xref>若要计算以进行转换。"
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "用于转换的上下文信息。"
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果<code> value </code>可以转换为<xref:System.String>; 否则为<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。</xref:System.String>"
  overload: System.Windows.Media.Converters.PointCollectionValueSerializer.CanConvertToString*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "Occurs when <code>value</code> is not a <xref href=&quot;System.Windows.Media.PointCollection&quot;></xref>."
  platform:
  - net462
- uid: System.Windows.Media.Converters.PointCollectionValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.PointCollectionValueSerializer
  langs:
  - csharp
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: PointCollectionValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.PointCollectionValueSerializer.ConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Converters
  summary: "将转换<xref:System.String>到<xref href=&quot;System.Windows.Media.PointCollection&quot;> </xref>。</xref:System.String>"
  syntax:
    content: public override object ConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: "<xref:System.String>值将转换为<xref href=&quot;System.Windows.Media.PointCollection&quot;> </xref>。</xref:System.String>"
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "用于转换的上下文信息。"
    return:
      type: System.Object
      description: "新实例<xref href=&quot;System.Windows.Media.PointCollection&quot;></xref>根据所提供<code> value </code>。"
  overload: System.Windows.Media.Converters.PointCollectionValueSerializer.ConvertFromString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Media.Converters.PointCollectionValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.PointCollectionValueSerializer
  langs:
  - csharp
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: PointCollectionValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.PointCollectionValueSerializer.ConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Converters
  summary: "将转换的实例<xref href=&quot;System.Windows.Media.PointCollection&quot;></xref>到<xref:System.String>。</xref:System.String>"
  syntax:
    content: public override string ConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: "实例<xref href=&quot;System.Windows.Media.PointCollection&quot;></xref>若要计算以进行转换。"
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "用于转换的上下文信息。"
    return:
      type: System.String
      description: "A<xref:System.String>表示形式提供<xref href=&quot;System.Windows.Media.PointCollection&quot;></xref>对象。</xref:System.String>"
  overload: System.Windows.Media.Converters.PointCollectionValueSerializer.ConvertToString*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Windows.Markup.ValueSerializer
  isExternal: false
  name: System.Windows.Markup.ValueSerializer
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.Windows.Media.Converters.PointCollectionValueSerializer.#ctor
  parent: System.Windows.Media.Converters.PointCollectionValueSerializer
  isExternal: false
  name: PointCollectionValueSerializer()
  nameWithType: PointCollectionValueSerializer.PointCollectionValueSerializer()
  fullName: System.Windows.Media.Converters.PointCollectionValueSerializer.PointCollectionValueSerializer()
- uid: System.Windows.Media.Converters.PointCollectionValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.PointCollectionValueSerializer
  isExternal: false
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: PointCollectionValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.PointCollectionValueSerializer.CanConvertFromString(String,IValueSerializerContext)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: System.Windows.Media.Converters.PointCollectionValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.PointCollectionValueSerializer
  isExternal: false
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: PointCollectionValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.PointCollectionValueSerializer.CanConvertToString(Object,IValueSerializerContext)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Windows.Media.Converters.PointCollectionValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.PointCollectionValueSerializer
  isExternal: false
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: PointCollectionValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.PointCollectionValueSerializer.ConvertFromString(String,IValueSerializerContext)
- uid: System.Windows.Media.Converters.PointCollectionValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.PointCollectionValueSerializer
  isExternal: false
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: PointCollectionValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.PointCollectionValueSerializer.ConvertToString(Object,IValueSerializerContext)
- uid: System.Windows.Media.Converters.PointCollectionValueSerializer.#ctor*
  parent: System.Windows.Media.Converters.PointCollectionValueSerializer
  isExternal: false
  name: PointCollectionValueSerializer
  nameWithType: PointCollectionValueSerializer.PointCollectionValueSerializer
- uid: System.Windows.Media.Converters.PointCollectionValueSerializer.CanConvertFromString*
  parent: System.Windows.Media.Converters.PointCollectionValueSerializer
  isExternal: false
  name: CanConvertFromString
  nameWithType: PointCollectionValueSerializer.CanConvertFromString
- uid: System.Windows.Media.Converters.PointCollectionValueSerializer.CanConvertToString*
  parent: System.Windows.Media.Converters.PointCollectionValueSerializer
  isExternal: false
  name: CanConvertToString
  nameWithType: PointCollectionValueSerializer.CanConvertToString
- uid: System.Windows.Media.Converters.PointCollectionValueSerializer.ConvertFromString*
  parent: System.Windows.Media.Converters.PointCollectionValueSerializer
  isExternal: false
  name: ConvertFromString
  nameWithType: PointCollectionValueSerializer.ConvertFromString
- uid: System.Windows.Media.Converters.PointCollectionValueSerializer.ConvertToString*
  parent: System.Windows.Media.Converters.PointCollectionValueSerializer
  isExternal: false
  name: ConvertToString
  nameWithType: PointCollectionValueSerializer.ConvertToString
